# Generated by Django 4.2.21 on 2025-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_task', models.TextField(blank=True)),
                ('time_start', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
