# Generated by Django 4.2.21 on 2025-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
